//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Decide
{
    using System;
    using System.Collections.Generic;
    
    public partial class DecisionHistory
    {
        public DecisionHistory()
        {
            this.Decisions = new HashSet<Decision>();
        }
    
        public int Id { get; set; }
        public string Version { get; set; }
        public string DateTime { get; set; }
    
        public virtual ICollection<Decision> Decisions { get; set; }
    }
}
