//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Decide
{
    using System;
    using System.Collections.Generic;
    
    public partial class Group : Entity
    {
        public Group()
        {
            this.People = new HashSet<Person>();
            this.GroupDecisions = new HashSet<GroupDecision>();
        }
    
    
        public virtual ICollection<Person> People { get; set; }
        public virtual ICollection<GroupDecision> GroupDecisions { get; set; }
    }
}
