//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Decide
{
    using System;
    using System.Collections.Generic;
    
    public partial class Options
    {
        public Options()
        {
            this.Factors = new HashSet<Factor>();
            this.Ratings = new HashSet<Rating>();
        }
    
        public int Id { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime DateModified { get; set; }
        public bool IsMostPopular { get; set; }
        public bool IsLeastPopular { get; set; }
        public string Version { get; set; }
        public bool Chosen { get; set; }
        public System.DateTime TimeSelected { get; set; }
        public string IsHeart { get; set; }
        public string IsHead { get; set; }
    
        public virtual ICollection<Factor> Factors { get; set; }
        public virtual Decision Decision { get; set; }
        public virtual Entity Entity { get; set; }
        public virtual ICollection<Rating> Ratings { get; set; }
    }
}
