//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Decide
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rating
    {
        public int Id { get; set; }
        public string Summary { get; set; }
        public string Description { get; set; }
        public long Value { get; set; }
    
        public virtual Decision Decision { get; set; }
        public virtual Options Option { get; set; }
        public virtual Entity Entity { get; set; }
        public virtual Factor Factor { get; set; }
        public virtual ComplexDecision ComplexDecision { get; set; }
    }
}
