//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Decide
{
    using System;
    using System.Collections.Generic;
    
    public partial class SocialIdentities_GooglePlus
    {
        public string Identity { get; set; }
        public string Publish { get; set; }
        public string PublishAlways { get; set; }
        public int Id { get; set; }
    
        public virtual SocialIdentity SocialIdentity { get; set; }
    }
}
