//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Decide
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class StorageModelContainer : DbContext
    {
        public StorageModelContainer()
            : base("name=StorageModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Factor> Factors { get; set; }
        public DbSet<Decision> Decisions { get; set; }
        public DbSet<Role> Roles { get; set; }
        public DbSet<Entity> Entities { get; set; }
        public DbSet<Session> Sessions { get; set; }
        public DbSet<Wisdom> Wisdom { get; set; }
        public DbSet<Options> Options { get; set; }
        public DbSet<Reputation> Reputations { get; set; }
        public DbSet<ComplexDecision> ComplexDecisions { get; set; }
        public DbSet<ComplexDecisionHistory> ComplexDecisionHistories { get; set; }
        public DbSet<Rating> Ratings { get; set; }
        public DbSet<DecisionHistory> DecisionHistories { get; set; }
        public DbSet<DecusionHistory> DecusionHistories { get; set; }
        public DbSet<SocialIdentity> SocialIdentities { get; set; }
        public DbSet<SocialIdentities_Facebook> SocialIdentities_Facebook { get; set; }
        public DbSet<SocialIdentities_GooglePlus> SocialIdentities_GooglePlus { get; set; }
        public DbSet<SocialIdentities_Twitter> SocialIdentities_Twitter { get; set; }
    }
}
